apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Values.labels.app }}
    component: {{ .Values.labels.component }}
data:
  appName: {{ .Values.config.appName | quote }}
  environment: {{ .Values.config.environment | quote }}
  debug: {{ .Values.config.debug | quote }}
